# Generated by Django 5.2.1 on 2025-05-17 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                ("code", models.CharField(max_length=5, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("official_name", models.CharField(max_length=500)),
                ("region", models.CharField(max_length=100)),
                ("subregion", models.CharField(max_length=100)),
                ("independent", models.BooleanField(null=True)),
                ("google_maps_url", models.URLField(blank=True, max_length=500, null=True)),
                ("openstreetmap_url", models.URLField(blank=True, max_length=500, null=True)),
                ("capital_name", models.CharField(blank=True, max_length=100, null=True)),
                ("capital_latitude", models.FloatField(blank=True, null=True)),
                ("capital_longitude", models.FloatField(blank=True, null=True)),
                ("flag_png_url", models.URLField(blank=True, max_length=500, null=True)),
                ("flag_svg_url", models.URLField(blank=True, max_length=500, null=True)),
                ("flag_alt", models.TextField(blank=True, max_length=2000, null=True)),
                ("coat_of_arms_png_url", models.URLField(blank=True, max_length=500, null=True)),
                ("coat_of_arms_svg_url", models.URLField(blank=True, max_length=500, null=True)),
                ("borders", models.ManyToManyField(blank=True, to="api.country")),
            ],
            options={
                "verbose_name_plural": "countries",
            },
        ),
        migrations.CreateModel(
            name="NameCountryProbability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("probability", models.FloatField()),
                ("count_of_requests", models.IntegerField(default=0)),
                ("last_accessed", models.DateTimeField(blank=True, null=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.country"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "name country probabilities",
            },
        ),
        migrations.AddIndex(
            model_name="country",
            index=models.Index(fields=["code"], name="api_country_code_e43e16_idx"),
        ),
        migrations.AddIndex(
            model_name="country",
            index=models.Index(fields=["name"], name="api_country_name_482826_idx"),
        ),
        migrations.AddIndex(
            model_name="namecountryprobability",
            index=models.Index(fields=["name"], name="api_namecou_name_e65c66_idx"),
        ),
        migrations.AddIndex(
            model_name="namecountryprobability",
            index=models.Index(fields=["country"], name="api_namecou_country_aa92fb_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="namecountryprobability",
            unique_together={("name", "country")},
        ),
    ]
